document.addEventListener("DOMContentLoaded", () => {
    let criminales = window.sispolCriminalesData || [], perfilActual = null;
    const $ = (id) => document.getElementById(id);
    const scanList = $("scanList"), searchForm = $("searchForm"), searchInput = $("nombreBusqueda"), searchType = $("tipoBusqueda"), btnBuscar = $("btnBuscar"), statusBusqueda = $("statusBusqueda"), scanCounter = $("scanCounter"), profileSummary = $("profileSummary"), profileCreatePanel = $("profileCreatePanel"), profilePlaceholder = $("profilePlaceholder"), crimePanel = $("crimePanel");
    const perfilNombre = $("perfilNombre"), perfilCharacterId = $("perfilCharacterId"), perfilDni = $("perfilDni"), perfilEdad = $("perfilEdad"), perfilNacionalidad = $("perfilNacionalidad"), perfilStatus = $("perfilStatus"), perfilMultas = $("perfilMultas"), perfilCrimenes = $("perfilCrimenes"), perfilBiometrico = $("perfilBiometrico"), perfilReferencias = $("perfilReferencias"), perfilFoto = $("perfilFoto");
    const createNombre = $("createNombre"), createCharacterId = $("createCharacterId"), createDni = $("createDni"), createEdad = $("createEdad"), createFoto = $("createFoto"), createNacionalidad = $("createNacionalidad"), createStatus = $("createStatus"), createAdn = $("createAdn"), createHuella = $("createHuella"), btnCrearPerfil = $("btnCrearPerfil");
    const crimeList = $("crimeList"), statusSelect = $("statusSelect"), crimeForm = $("crimeForm"), nuevoCrimen = $("nuevoCrimen"), nuevaSancion = $("nuevaSancion"), btnAgregarCrimen = $("btnAgregarCrimen"), scanFlash = $("scanFlash");
    const normalizar = (value) => String(value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim().toUpperCase();
    const setStatus = (text, type = "") => { statusBusqueda.textContent = text; statusBusqueda.className = "status-line" + (type ? " " + type : ""); };
    const pulseFlash = () => { scanFlash.classList.remove("run"); void scanFlash.offsetWidth; scanFlash.classList.add("run"); };
    const updateCounter = () => { scanCounter.textContent = `ARCHIVOS: ${criminales.length}`; };
    const same = (a,b) => String(a) === String(b);
    function image(url, klass) { if (!url) { const x=document.createElement("div"); x.className=`${klass} empty`; x.textContent="SIN FOTO"; return x; } const x=document.createElement("img"); x.className=klass; x.src=url; x.alt="Foto de perfil"; x.onerror=()=>x.replaceWith(image("",klass)); return x; }
    function biometric(p) { const flags=[]; if(p.adn)flags.push("ADN"); if(p.huella_dactilar)flags.push("HUELLA DACTILAR"); return flags.length&&p.character_id?`PERFIL BIOMÉTRICO: ${p.character_id} (${flags.join(" + ")})`:"SIN DATOS BIOMÉTRICOS"; }
    function renderCards() { scanList.innerHTML=""; criminales.forEach((p)=>{const card=document.createElement("article"),head=document.createElement("div"),details=document.createElement("div"),title=document.createElement("div"),meta=document.createElement("div");card.className="scan-card";head.className="scan-card-head";title.className="scan-name";meta.className="scan-meta";title.textContent=p.nombre; [["CHARACTER ID",p.character_id||"-"],["BIOMÉTRICO",p.adn||p.huella_dactilar?"SÍ":"NO"],["CRÍMENES",p.crimenes_count||0],["MULTAS",p.multas_count||0]].forEach(([k,v])=>{const l=document.createElement("div");l.textContent=`${k}: ${v}`;meta.append(l);});head.append(image(p.foto,"criminal-photo"));details.append(title,meta);head.append(details);card.append(head);card.addEventListener("click",()=>p.unregistered?showCandidate(p):showProfile(p));scanList.append(card);});}
    function fill(p) { perfilNombre.textContent=p.nombre||"-";perfilCharacterId.textContent=p.character_id||"-";perfilDni.textContent=p.dni||"-";perfilEdad.textContent=p.edad??"-";perfilNacionalidad.textContent=p.nacionalidad||"-";perfilStatus.textContent=p.status||"-";perfilMultas.textContent=Number(p.multas_count||0);perfilCrimenes.textContent=Number(p.crimenes_count||0);perfilBiometrico.textContent=biometric(p);perfilReferencias.textContent=(p.referencias||[]).join(" · ")||"SIN COINCIDENCIAS";perfilFoto.replaceChildren(image(p.foto,"profile-photo")); }
    function renderCrimes(){crimeList.innerHTML="";const crimes=perfilActual?.crimenes||[];if(!crimes.length){crimeList.innerHTML='<li class="crime-item">Sin crímenes registrados.</li>';return;}crimes.forEach((c)=>{const x=document.createElement("li");x.className="crime-item";x.textContent=`${c.delito||c} / SANCIÓN: ${c.sancion||"SIN SANCIÓN ESPECIFICADA"}`;crimeList.append(x);});}
    function clear(message){perfilActual=null;profileSummary.style.display="none";profileCreatePanel.style.display="none";profilePlaceholder.style.display="flex";profilePlaceholder.textContent=message;crimePanel.style.display="none";}
    function showProfile(p){perfilActual=p;fill(p);profileSummary.style.display="grid";profilePlaceholder.style.display="none";profileCreatePanel.style.display="none";crimePanel.style.display="flex";statusSelect.value=p.status||"EN LIBERTAD";statusSelect.disabled=false;nuevoCrimen.disabled=false;nuevaSancion.disabled=false;btnAgregarCrimen.disabled=false;renderCrimes();setStatus(`Perfil cargado: ${p.nombre}`,"success");}
    function showCandidate(p){perfilActual=null;fill(p);profileSummary.style.display="grid";profilePlaceholder.style.display="none";crimePanel.style.display="none";profileCreatePanel.style.display="grid";createNombre.value=p.nombre||"";createCharacterId.value=p.character_id||"";createDni.value="";createEdad.value="";createFoto.value="";createNacionalidad.value="";createStatus.value="EN LIBERTAD";createAdn.checked=false;createHuella.checked=false;setStatus(`Personaje localizado sin perfil SISPOL: ${p.nombre}`,"success");}
    function replace(p){const i=criminales.findIndex((x)=>same(x.id,p.id));if(i>=0)criminales[i]=p;else criminales.push(p);}
    async function request(url,options={}){const r=await fetch(url,options),data=await r.json();if(!r.ok||!data.ok)throw new Error(data.message||"No se pudo completar la operación.");return data.data;}
    searchForm.addEventListener("submit",async(e)=>{e.preventDefault();const q=searchInput.value.trim();if(!q){clear("Escribe un nombre o Character ID para iniciar la búsqueda.");setStatus("Ingresa un dato de búsqueda.","error");return;}btnBuscar.disabled=true;pulseFlash();clear("Consultando archivos de personajes...");try{const found=await request(`../api/criminals.php?q=${encodeURIComponent(q)}&field=${encodeURIComponent(searchType.value)}`);if(!found.length){clear("No se encontraron personajes.");setStatus("Sin coincidencias en characters.","error");return;}criminales=found;renderCards();found[0].unregistered?showCandidate(found[0]):showProfile(found[0]);}catch(err){clear("No fue posible completar la consulta.");setStatus(err.message,"error");}finally{btnBuscar.disabled=false;}});
    btnCrearPerfil.addEventListener("click",async()=>{const payload={action:"create",nombre:normalizar(createNombre.value),character_id:createCharacterId.value.trim(),dni:createDni.value.trim().toUpperCase(),edad:createEdad.value.trim(),foto:createFoto.value.trim(),nacionalidad:normalizar(createNacionalidad.value),status:createStatus.value,adn:createAdn.checked,huella_dactilar:createHuella.checked};if(!payload.nombre||!payload.character_id){setStatus("Selecciona un personaje válido antes de registrarlo.","error");return;}if(payload.foto&&!/^https?:\/\//i.test(payload.foto)){setStatus("La foto debe ser una URL válida.","error");return;}btnCrearPerfil.disabled=true;try{const p=await request("../api/criminals.php",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});replace(p);renderCards();updateCounter();showProfile(p);setStatus(`Perfil registrado: ${p.nombre}`,"success");}catch(err){setStatus(err.message,"error");}finally{btnCrearPerfil.disabled=false;}});
    crimeForm.addEventListener("submit",async(e)=>{e.preventDefault();if(!perfilActual)return;const delito=normalizar(nuevoCrimen.value),sancion=normalizar(nuevaSancion.value);if((delito&& !sancion)||(!delito&&sancion)){setStatus("Para añadir un crimen completa también su sanción.","error");return;}btnAgregarCrimen.disabled=true;try{const p=await request("../api/criminals.php",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save_history",id:perfilActual.id,status:statusSelect.value,delito,sancion})});replace(p);renderCards();showProfile(p);nuevoCrimen.value="";nuevaSancion.value="";}catch(err){setStatus(err.message,"error");}finally{btnAgregarCrimen.disabled=false;}});
    renderCards();updateCounter();clear("Ejecuta una búsqueda para cargar la ficha del sospechoso.");
});
