<?php
require_once __DIR__.'/database.php';
function rangers_vehicle_fines_text(int $n):string{return $n<=0?'SIN MULTAS':($n===1?'1 MULTA PENDIENTE':$n.' MULTAS PENDIENTES');} function rangers_format_currency(float $n):string{return '$ '.number_format($n,0,',','.');} function rangers_parse_currency(string $v):float{$v=str_replace(',','.',str_replace('.','',preg_replace('/[^0-9,.]/','',$v)));return is_numeric($v)?(float)$v:0;}
function rangers_vehicle_view(string $id,array $x):array{return ['id'=>$id,'propietario'=>strtoupper($x['owner_name']??'SIN PROPIETARIO REGISTRADO'),'modelo'=>strtoupper($x['model']??''),'matricula'=>strtoupper($x['plate']??''),'color'=>strtoupper($x['color']??''),'descripcion'=>strtoupper($x['description']??''),'multas'=>rangers_vehicle_fines_text((int)($x['fines_count']??0)),'status'=>strtoupper($x['embargo_status']??'SIN EMBARGO'),'multas_count'=>(int)($x['fines_count']??0)];}
function rangers_fetch_vehicles():array{$o=[];foreach(rangers_firebase_keyed_rows('vehicles') as $id=>$x)$o[]=rangers_vehicle_view($id,$x);return $o;} function rangers_fetch_vehicle_by_id(string $id):?array{$x=rangers_firebase_get('vehicles/'.$id);return $x?rangers_vehicle_view($id,$x):null;}
function rangers_create_vehicle(array $d):array{$id=rangers_new_id();rangers_firebase_set('vehicles/'.$id,['owner_name'=>strtoupper(trim($d['propietario']??'SIN PROPIETARIO REGISTRADO')),'model'=>strtoupper(trim($d['modelo']??'')),'plate'=>strtoupper(trim($d['matricula']??'')),'color'=>strtoupper(trim($d['color']??'')),'description'=>strtoupper(trim($d['descripcion']??'')),'fines_count'=>(int)($d['multas_count']??0),'embargo_status'=>strtoupper(trim($d['status']??'SIN EMBARGO'))]);return rangers_fetch_vehicle_by_id($id);}
function rangers_update_vehicle(array $d):array{$id=(string)$d['id'];rangers_firebase_update('vehicles/'.$id,['owner_name'=>strtoupper(trim($d['propietario']??'SIN PROPIETARIO REGISTRADO')),'model'=>strtoupper(trim($d['modelo']??'')),'plate'=>strtoupper(trim($d['matricula']??'')),'color'=>strtoupper(trim($d['color']??'')),'description'=>strtoupper(trim($d['descripcion']??'')),'embargo_status'=>strtoupper(trim($d['status']??'SIN EMBARGO'))]);return rangers_fetch_vehicle_by_id($id);}
function rangers_fetch_traffic_fines():array{$x=[];foreach(rangers_firebase_keyed_rows('traffic_fines') as $key=>$fine)$x[]=['storage_id'=>$key]+$fine;usort($x,fn($a,$b)=>strcmp($b['issued_at']??'',$a['issued_at']??''));return array_map(fn($f)=>['id'=>$f['fine_code'],'storage_id'=>$f['storage_id'],'matricula'=>$f['plate'],'modelo'=>$f['model'],'color'=>$f['color']??'','falta'=>$f['offense'],'valor'=>rangers_format_currency((float)$f['amount']),'observaciones'=>$f['observations']??'','fecha'=>$f['issued_at']??''],$x);}
function rangers_create_traffic_fine(array $d, mixed $uid, string $name):array{$plate=strtoupper(trim($d['matricula']??''));$vehicle=null;foreach(rangers_firebase_keyed_rows('vehicles') as $id=>$v)if(strtoupper($v['plate']??'')===$plate){$vehicle=[$id,$v];break;}if($vehicle){[$id,$v]=$vehicle;rangers_firebase_update('vehicles/'.$id,['model'=>strtoupper(trim($d['modelo']??'')),'color'=>strtoupper(trim($d['color']??'')),'fines_count'=>(int)($v['fines_count']??0)+1]);}else{$v=rangers_create_vehicle(['modelo'=>$d['modelo']??'','matricula'=>$plate,'color'=>$d['color']??'','descripcion'=>$d['observaciones']??'','multas_count'=>1]);$id=$v['id'];}$code='MT-'.date('ymdHis').random_int(10,99);$amount=rangers_parse_currency($d['valor']??'0');rangers_firebase_set('traffic_fines/'.rangers_new_id(),['fine_code'=>$code,'vehicle_id'=>$id,'plate'=>$plate,'model'=>strtoupper(trim($d['modelo']??'')),'color'=>strtoupper(trim($d['color']??'')),'offense'=>strtoupper(trim($d['falta']??'')),'amount'=>$amount,'observations'=>strtoupper(trim($d['observaciones']??'')),'issued_by_user_id'=>$uid,'issued_by_name'=>strtoupper($name),'issued_at'=>date('Y-m-d H:i:s')]);return ['fine'=>['id'=>$code,'matricula'=>$plate,'modelo'=>strtoupper($d['modelo']??''),'color'=>strtoupper($d['color']??''),'falta'=>strtoupper($d['falta']??''),'valor'=>rangers_format_currency($amount),'observaciones'=>strtoupper($d['observaciones']??'')],'vehicle'=>rangers_fetch_vehicle_by_id($id)];}
function rangers_update_traffic_fine(string $id,array $d):?array{$fine=rangers_firebase_get('traffic_fines/'.$id);if(!$fine)throw new RuntimeException('Multa no encontrada.');$data=['plate'=>strtoupper(trim($d['matricula']??$fine['plate'])),'model'=>strtoupper(trim($d['modelo']??$fine['model'])),'color'=>strtoupper(trim($d['color']??$fine['color']??'')),'offense'=>strtoupper(trim($d['falta']??$fine['offense'])),'amount'=>rangers_parse_currency((string)($d['valor']??$fine['amount'])),'observations'=>strtoupper(trim($d['observaciones']??$fine['observations']??'')),'updated_at'=>date('Y-m-d H:i:s')];rangers_firebase_update('traffic_fines/'.$id,$data);if(!empty($fine['vehicle_id']))rangers_firebase_update('vehicles/'.$fine['vehicle_id'],['plate'=>$data['plate'],'model'=>$data['model'],'color'=>$data['color']]);foreach(rangers_fetch_traffic_fines() as $item)if($item['storage_id']===$id)return $item;return null;}
function rangers_delete_traffic_fine(string $id):void{$fine=rangers_firebase_get('traffic_fines/'.$id);if(!$fine)throw new RuntimeException('Multa no encontrada.');if(!empty($fine['vehicle_id'])){$vehicle=rangers_firebase_get('vehicles/'.$fine['vehicle_id']);if($vehicle)rangers_firebase_update('vehicles/'.$fine['vehicle_id'],['fines_count'=>max(0,(int)($vehicle['fines_count']??0)-1)]);}rangers_firebase_delete('traffic_fines/'.$id);}
