<?php
session_start();
if (!isset($_SESSION['usuario'])) { header('Location: ../index.php'); exit; }
require_once __DIR__ . '/access_control.php';
if (!sispol_puede_entrar_asuntos_internos($_SESSION['rango'] ?? '')) { header('Location: ../panel.php'); exit; }
require_once __DIR__ . '/../lib/internal_investigations.php';

$user = strtoupper(trim($_SESSION['usuario'] ?? 'USUARIO'));
$error = '';
$saved = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        $saved = rangers_create_internal_investigation($_POST, $user);
    } catch (Throwable $exception) { $error = $exception->getMessage(); }
}
?>
<!DOCTYPE html>
<html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Nueva investigación interna</title><link rel="stylesheet" href="../loader_sispol.css">
<style>
:root{--green:#d7ee63;--bar:#acd52d;--soft:#dff58b;--red:#ff6868}*{box-sizing:border-box}body{margin:0;background:#000;color:var(--green);font-family:"Courier New",monospace}body:before{content:"";position:fixed;inset:0;pointer-events:none;background:repeating-linear-gradient(to bottom,rgba(255,255,255,.025) 0 1px,transparent 1px 4px)}.wrap{position:relative;width:min(1050px,calc(100% - 36px));margin:32px auto}.top{background:var(--bar);color:#111;padding:12px 16px;font-size:25px;font-weight:bold}.info,.actions{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;margin:16px 0;font-weight:bold}.line{height:10px;background:repeating-linear-gradient(to right,var(--green) 0 8px,transparent 8px 16px);margin:14px 0}.panel{border:1px solid rgba(215,238,99,.32);padding:18px;background:repeating-linear-gradient(-45deg,rgba(163,214,63,.08) 0 12px,rgba(163,214,63,.03) 12px 24px)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.full{grid-column:1/-1}label{display:block;color:#fff;font-size:14px;font-weight:bold;margin-bottom:6px;text-transform:uppercase}input,select,textarea{width:100%;background:#000;border:2px solid rgba(172,213,45,.48);color:var(--soft);padding:11px;font:16px "Courier New",monospace;text-transform:uppercase}textarea{min-height:140px;resize:vertical}.button{padding:11px 16px;border:2px solid var(--green);background:#000;color:var(--green);font:bold 16px "Courier New",monospace;text-decoration:none;cursor:pointer;text-transform:uppercase}.button:hover{background:var(--green);color:#000}.evidence-row{display:flex;gap:8px;margin-top:8px}.evidence-row input{flex:1}.remove{border:1px solid var(--red);background:#000;color:var(--red);padding:0 12px;cursor:pointer}.msg{margin:14px 0;padding:12px;border-left:4px solid var(--green);background:#111;font-weight:bold}.error{border-color:var(--red);color:var(--red)}@media(max-width:700px){.grid{grid-template-columns:1fr}.full{grid-column:auto}.wrap{width:calc(100% - 22px);margin:12px auto}.top{font-size:19px}}
</style></head><body><div class="wrap"><div class="top">NUEVA INVESTIGACIÓN INTERNA</div><div class="info"><span>JEFATURA: <?php echo htmlspecialchars($user); ?></span><span>MÓDULO: ASUNTOS INTERNOS</span></div><div class="line"></div>
<?php if ($saved): ?><div class="msg">REGISTRO GUARDADO: <?php echo htmlspecialchars($saved['case_code']); ?> · <a href="investigaciones_internas.php" style="color:inherit">VOLVER AL LISTADO</a></div><?php elseif ($error): ?><div class="msg error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?>
<form class="panel" method="post"><div class="grid"><div class="full"><label for="titulo">Nombre del caso</label><input id="titulo" name="titulo" required></div><div><label for="jefatura">Jefatura a cargo</label><input id="jefatura" name="jefatura" value="<?php echo htmlspecialchars($user); ?>" required></div><div><label for="fecha_hora">Fecha y hora</label><input id="fecha_hora" name="fecha_hora" type="datetime-local" value="<?php echo date('Y-m-d\TH:i'); ?>" required></div><div><label for="nivel">Nivel de investigación</label><select id="nivel" name="nivel"><option value="CLASE A">CLASE A · GRAVE</option><option value="CLASE B">CLASE B · INTERMEDIA</option><option value="CLASE C">CLASE C · LEVE</option></select></div><div><label for="status">Status</label><select id="status" name="status"><option value="ABIERTO">ABIERTO</option><option value="CERRADO">CERRADO</option></select></div><div class="full"><label for="descripcion">Descripción</label><textarea id="descripcion" name="descripcion" required></textarea></div><div class="full"><label>Evidencias gráficas · enlaces Imgur o similar</label><div id="evidenceList"><div class="evidence-row"><input name="evidencias[]" type="url" placeholder="https://i.imgur.com/imagen.jpg"><button class="remove" type="button" aria-label="Quitar evidencia">×</button></div></div><button class="button" type="button" id="addEvidence" style="margin-top:10px">+ Añadir enlace</button></div></div><div class="actions"><a class="button" href="investigaciones_internas.php">Cancelar</a><button class="button" type="submit">Guardar investigación</button></div></form></div><script>const list=document.getElementById('evidenceList');document.getElementById('addEvidence').onclick=()=>{const row=document.createElement('div');row.className='evidence-row';row.innerHTML='<input name="evidencias[]" type="url" placeholder="https://i.imgur.com/imagen.jpg"><button class="remove" type="button" aria-label="Quitar evidencia">×</button>';list.appendChild(row)};list.onclick=e=>{if(e.target.classList.contains('remove')&&list.children.length>1)e.target.parentElement.remove()};</script></body></html>
